# Generated by Django 5.0.6 on 2024-06-26 19:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TB_BU',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bu_name', models.TextField(max_length=200)),
                ('bu_cod', models.TextField(max_length=20)),
                ('bu_linkfolder', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TB_CUSTOMERSEGMENT',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TB_DEPARTAMENT',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TB_OPORESTIMATOR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TB_OPORTAGS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TB_OPORTCONTRACT',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TB_OPORTLOSS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TB_OPORTSTAGE',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('factor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TB_OPORTUNITYCHANCE',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('factor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TB_PM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TB_TEAMMEMBER',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('email', models.TextField(max_length=50, unique=True)),
                ('position', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TB_CUSTOMER',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('companyname', models.TextField(max_length=200, unique=True)),
                ('name', models.TextField(max_length=200, unique=True)),
                ('teamsname', models.TextField(max_length=200, unique=True)),
                ('cnpj', models.TextField(max_length=20, unique=True)),
                ('ie', models.TextField(max_length=20, null=True, unique=True)),
                ('province', models.TextField(max_length=20)),
                ('city', models.TextField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('zipcoud', models.TextField(max_length=20)),
                ('site', models.TextField(max_length=200)),
                ('address', models.TextField(max_length=200)),
                ('fk_customer_segment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_customersegment')),
            ],
        ),
        migrations.CreateModel(
            name='TB_CONTACT',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('email', models.TextField(max_length=100, unique=True)),
                ('phone', models.TextField(max_length=50)),
                ('celphone', models.TextField(max_length=50)),
                ('fk_contact_customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_customer')),
                ('fk_contact_departament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_departament')),
                ('fk_contact_teammember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_teammember')),
            ],
        ),
        migrations.CreateModel(
            name='TB_LEAD',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimatedprice', models.FloatField()),
                ('name', models.TextField(max_length=200)),
                ('description', models.TextField()),
                ('duedate', models.DateField()),
                ('created', models.DateField()),
                ('createdby', models.IntegerField()),
                ('fk_lead_contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_contact')),
            ],
        ),
        migrations.CreateModel(
            name='TB_OPORTUNITY',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.IntegerField(unique=True)),
                ('cod', models.TextField(max_length=20)),
                ('name', models.TextField(max_length=200)),
                ('mustwin', models.BooleanField()),
                ('estimatedagreement', models.DateField()),
                ('serviceprice', models.FloatField()),
                ('materialprice', models.FloatField()),
                ('softwareprice', models.FloatField()),
                ('expenseprice', models.FloatField()),
                ('taxes', models.FloatField()),
                ('totalprice', models.FloatField()),
                ('potentialprice', models.FloatField()),
                ('extrascope', models.BooleanField()),
                ('linkfolder', models.TextField(max_length=200, null=True, unique=True)),
                ('finisheddate', models.DateField(null=True)),
                ('finishedprice', models.FloatField(null=True)),
                ('supplyregister', models.CharField(max_length=50, null=True)),
                ('fk_oportunity_bu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_bu')),
                ('fk_oportunity_contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_contact')),
                ('fk_oportunity_customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_customer')),
                ('fk_oportunity_lead_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_lead')),
                ('fk_oportunity_oporcontract_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_oportcontract')),
                ('fk_oportunity_oporestimator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_oporestimator')),
                ('fk_oportunity_oporloss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_oportloss')),
                ('fk_oportunity_oporstage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_oportstage')),
                ('fk_oportunity_oporchance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_oportunitychance')),
            ],
        ),
        migrations.CreateModel(
            name='TB_FOLLOWUP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duedate', models.DateField()),
                ('objective', models.TextField()),
                ('date', models.DateField()),
                ('report', models.TextField()),
                ('fk_followup_oportunity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_oportunity')),
            ],
        ),
        migrations.CreateModel(
            name='TB_PROJECT',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cod', models.TextField(max_length=20, unique=True)),
                ('desc', models.TextField(max_length=200)),
                ('start', models.DateField()),
                ('finish', models.DateField()),
                ('contract', models.CharField(max_length=200)),
                ('constcenter', models.BooleanField()),
                ('linkfoldermanagement', models.TextField(max_length=200)),
                ('linkfoldertech', models.TextField(max_length=200)),
                ('linkfolderbackup', models.TextField(max_length=200)),
                ('fk_project_bu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_bu')),
                ('fk_project_customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_customer')),
                ('fk_project_pm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_pm')),
            ],
        ),
        migrations.CreateModel(
            name='PURCHASEORDER',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cod', models.TextField(max_length=20)),
                ('name', models.TextField(max_length=50)),
                ('iss', models.FloatField()),
                ('icms', models.FloatField()),
                ('ipi', models.FloatField()),
                ('pis', models.FloatField()),
                ('confins', models.FloatField()),
                ('totalservice', models.FloatField()),
                ('totalproduct', models.FloatField()),
                ('totalexpense', models.FloatField()),
                ('totalsoftware', models.FloatField()),
                ('linkfolder', models.TextField(max_length=200)),
                ('fk_purchaseorder_oportunity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_oportunity')),
                ('fk_purchaseorder_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_project')),
            ],
        ),
        migrations.AddField(
            model_name='tb_pm',
            name='fk_pm_teammember_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_teammember'),
        ),
        migrations.AddField(
            model_name='tb_oporestimator',
            name='fk_oporestimator_teammember',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_teammember'),
        ),
        migrations.CreateModel(
            name='TB_TIMELIFE',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('fk_timelife_oportunity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tb_oportunity')),
            ],
        ),
    ]
