# Generated by Django 5.0.6 on 2024-06-28 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CLIENT',
        ),
    ]
