# Generated by Django 5.0.6 on 2024-07-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_delete_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TB_BU',
            new_name='Bu',
        ),
        migrations.RenameModel(
            old_name='TB_CONTACT',
            new_name='Contact',
        ),
        migrations.RenameModel(
            old_name='TB_CUSTOMER',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='TB_DEPARTAMENT',
            new_name='Customersegment',
        ),
        migrations.RenameModel(
            old_name='TB_CUSTOMERSEGMENT',
            new_name='Departament',
        ),
        migrations.RenameModel(
            old_name='TB_FOLLOWUP',
            new_name='Followup',
        ),
        migrations.RenameModel(
            old_name='TB_LEAD',
            new_name='Lead',
        ),
        migrations.RenameModel(
            old_name='TB_PM',
            new_name='Oporestimator',
        ),
        migrations.RenameModel(
            old_name='TB_OPORTAGS',
            new_name='OPortags',
        ),
        migrations.RenameModel(
            old_name='TB_OPORTCONTRACT',
            new_name='Oportcontract',
        ),
        migrations.RenameModel(
            old_name='TB_OPORTLOSS',
            new_name='Oportloss',
        ),
        migrations.RenameModel(
            old_name='TB_OPORTSTAGE',
            new_name='Oportstage',
        ),
        migrations.RenameModel(
            old_name='TB_OPORTUNITY',
            new_name='Oportunity',
        ),
        migrations.RenameModel(
            old_name='TB_OPORTUNITYCHANCE',
            new_name='Oportunitychance',
        ),
        migrations.RenameModel(
            old_name='TB_OPORESTIMATOR',
            new_name='Pm',
        ),
        migrations.RenameModel(
            old_name='TB_PROJECT',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='TB_TEAMMEMBER',
            new_name='Teammember',
        ),
        migrations.RenameModel(
            old_name='TB_TIMELIFE',
            new_name='Timelife',
        ),
        migrations.RenameField(
            model_name='oporestimator',
            old_name='fk_pm_teammember_id',
            new_name='fk_oporestimator_teammember',
        ),
        migrations.RenameField(
            model_name='pm',
            old_name='fk_oporestimator_teammember',
            new_name='fk_pm_teammember_id',
        ),
    ]
