# Generated by Django 5.0.6 on 2024-07-01 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_rename_tb_bu_bu_rename_tb_contact_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='fk_contact_departament_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.departament'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fk_customer_segment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.customersegment'),
        ),
        migrations.AlterField(
            model_name='oportunity',
            name='fk_oportunity_oporestimator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.oporestimator'),
        ),
        migrations.AlterField(
            model_name='project',
            name='fk_project_pm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.pm'),
        ),
    ]
