# Generated by Django 5.0.6 on 2024-07-02 13:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_contact_fk_contact_departament_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunity',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
