# Generated by Django 5.0.6 on 2024-07-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_oportunity_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oportunity',
            name='mustwin',
        ),
        migrations.AlterField(
            model_name='oportunity',
            name='uid',
            field=models.IntegerField(unique=True),
        ),
    ]
