# Generated by Django 5.0.6 on 2024-07-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_remove_oportunity_mustwin_alter_oportunity_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunity',
            name='mustwin',
            field=models.BooleanField(null=True),
        ),
    ]
