# Generated by Django 5.0.6 on 2024-07-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_alter_oportunity_estimatedagreement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunity',
            name='cod',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='oportunity',
            name='uid',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
