# Generated by Django 5.0.6 on 2024-07-02 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_alter_oportunity_cod_alter_oportunity_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fk_project_bu_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.bu'),
        ),
    ]
