# Generated by Django 5.0.6 on 2024-07-02 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_alter_project_fk_project_bu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunity',
            name='cod',
            field=models.TextField(default='default_value', max_length=20),
        ),
        migrations.AlterField(
            model_name='oportunity',
            name='estimatedagreement',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='oportunity',
            name='expenseprice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='oportunity',
            name='extrascope',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='oportunity',
            name='materialprice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='oportunity',
            name='potentialprice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='oportunity',
            name='serviceprice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='oportunity',
            name='softwareprice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='oportunity',
            name='taxes',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='oportunity',
            name='totalprice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='oportunity',
            name='uid',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='fk_project_bu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.bu'),
        ),
    ]
